# 应用或包的名称
name: my_flutter_app
# 描述
description: A new Flutter application.
# 应用或包的版本号
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

# 应用或包依赖的其它包或插件
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  # 添加英语单词依赖包
  english_words: ^3.1.3
  # 上述方式为依赖PUB仓库
  # 当需要依赖本地包或者git包时可以使用如下方式
  #  dependencies:
  #    pkg1:
  #      path: ../../code/pkg1
  #  dependencies:
  #    pkg1:
  #      git:
  #        url: git://github.com/xxx/pkg1.git
  #  dependencies:
  #    package1:
  #      git:
  #        url: git://github.com/flutter/packages.git
  #        path: packages/package1



# 开发环境依赖的工具包（而不是flutter应用本身依赖的包）
dev_dependencies:
  flutter_test:
    sdk: flutter

# Flutter的相关配置
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # 应用资源管理
  assets:
    - assets/icon1.png
    - assets/icon2.png
    - assets/text.txt
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
